name: docker

on:
  schedule:
    - cron: '0 18 * * *'

defaults:
  run:
    shell: bash

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Set up go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}
          fetch-depth: 2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker images
        run: |
          export GOPATH=${GITHUB_WORKSPACE}/go
          export PATH=$PATH:$GOPATH/bin
          export DOCKER_REGISTRY=docker.io
          export IMAGE_TAG=latest
          make docker-push
        working-directory: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}